using Comonicon

include(joinpath(@__DIR__, "_analyse.jl"))

"""
Read the data for the 2024 GECCO paper from mlflow.
"""
@cast function prep()
    df = loadruns()
    _prep(df)
    return 0
end

"""
Plot the graphs used in the 2024 GECCO paper.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
"""
@cast function graphs(fpath)
    df = deserialize(fpath)
    _graphs(df)
    return 0
end

"""
Read the convergence data for the 2024 GECCO paper via SSH.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
"""
@cast function prepconv(fpath)
    df = deserialize(fpath)
    fitnesses = _prepconv(df)
    return 0
end

"""
Analyse convergence behaviour for the 2024 GECCO paper.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
- `fpathconv`: Path to the convergence data `.jls` file generated by `analyse.jl
  prepconv`.
"""
@cast function conv(fpath, fpathconv)
    df = deserialize(fpath)
    fitnesses = deserialize(fpathconv)
    _conv(df, fitnesses)
    return 0
end

@main
