using Comonicon

include(joinpath(@__DIR__, "_analyse.jl"))

"""
Read the data for the 2024 IWERL paper from mlflow.

# Args

- `tag`: Suffixed to the output path.
"""
@cast function prep(tag=nothing)
    df = _loadruns()
    _prep(df, tag)
    return 0
end

"""
Analyse train MSE behaviour of the variants.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
- `tag`: Suffixed to the output path.
"""
@cast function mse(fpath, tag=nothing)
    df = deserialize(fpath)
    _mse(df, tag)
    return 0
end

"""
Plot the graphs used in the 2024 IWERL paper.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
- `tag`: Suffixed to the output path.
"""
@cast function graphs(fpath, tag=nothing)
    df = deserialize(fpath)
    _graphs(df, tag)
    return 0
end

"""
Read the convergence data for the 2024 IWERL paper via SSH.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
- `tag`: Suffixed to the output path.
"""
@cast function prepconv(fpath, tag=nothing)
    df = deserialize(fpath)
    fitnesses = _prepconv(df, tag)
    return 0
end

"""
Analyse convergence behaviour for the 2024 IWERL paper.

# Args

- `fpath`: Path to the `.jls` file (a serialized `DataFrame` containing the
  paper's results; see the `prep` method in this file).
- `fpathconv`: Path to the convergence data `.jls` file generated by `analyse.jl
  prepconv`.
- `tag`: Suffixed to the output path.
"""
@cast function conv(fpath, fpathconv, tag=nothing)
    df = deserialize(fpath)
    fitnesses = deserialize(fpathconv)
    _conv(df, fitnesses, tag)
    return 0
end

@main
